// =============================================================================
// CONSTANTS_AND_GLOBAL_VARIABLES ----------------------------------------------
// ============================================================================{
// Additional Data type constants
//TODO: Update these to make a little more sense...  Also maybe use characters? (1 byte instead of 4?)
const BOOL = 0
const INT64 = 4
const UINT32 = 7
const UINT64 = 8
const BYTE = 11
const WORD = 12
const DWORD = 13
const STRING8 = 14

// Poll Registers //////////////////////////////////////////////////////////////
MB_POLL_REGISTERS <- [
    // "PROTO_VERSION",
    // "FW_VERSION",
    // "SERIAL_NUM",
    // "CAPABILITIES",
    // "SEC_RESET",
    // "SEC_SLEEP",
    // "SEC_CHARGER_TYPE",
    // "SEC_CHARGER_FORM_FACTOR",
    "ACTIVE",
    "AUTHORIZE_TYPE",
    "SESSION_TYPE",
    "AUTHORIZE_DATA",
    // "AUTHORIZE_STROBE",
    // "POWER_LIMIT_CONTROL",
    // "POWER_LIMIT",
    // "UPDATE_RATE",
    // "TIME",
    // "SEC_STATE_RESET",
    "COLD_LOAD_ENABLED",
    // "MIN_COLD_LOAD_TIME",
    // "MAX_COLD_LOAD_TIME",
    // "FIRMWARE_TRANSFER",
    // "FIRMWARE_WHOLE_CRC",
    // "FIRMWARE_BLOCK_CRC",
    // "FIRMWARE",
    // "FIRMWARE_NUM_BYTES",
    // "PROTOCOL_TYPE",
    "PROTOCOL_STATE",
    // "RESET_REASON",
    // "SEC_TEMP",
    // "OTHER_TEMPS",
    // "STATE_OF_CHARGE",
    // "REMAINING_AUTHORIZATION",
    // "REMAINING_CHARGE_TIME",
    "PERMANENT_ERROR_FLAG",
    "TEMP_ERROR",
    "ERROR_COUNT",
    "ERROR_CODE",
    "ERROR_DATA_1",
    "ERROR_DATA_2",
    "ERROR_DATA_3",
    "ERROR_DATA_4",
    "ERROR_READ",
    "ERROR_OVERFLOW",
    "GFCI_FAULTS_SESSION",
    // "LAST_READ_VOLTAGE",
    // "LAST_READ_CURRENT",
    "ENERGY_TOTAL_FOREVER",
    // "ENERGY_TOTAL_RESET",
    // "ENERGY_TOTAL_CHARGE",
    // "ENERGY_TOTAL_PLUG",
    // "CHARGE_SESSION_COUNT_FOREVER",
    // "CHARGE_SESSION_COUNT_RESET",
    // "PLUG_SESSION_COUNT_FOREVER",
    // "PLUG_SESSION_COUNT_RESET",
    // "BOOT_COUNT_FOREVER",
    // "BOOT_COUNT_RESET",
    // "POWER_LOSS_COUNT_FOREVER",
    // "POWER_LOSS_COUNT_RESET",
    // "AUTO_RECLOSE_TIME_REMAINING",
    // "COLD_LOAD_TIME_REMAINING",
    // "FACTORY_PASSWORD",
    // "FACTORY_NAMEPLATE_RATING",
    // "CAL_VOLTAGE_GAIN",
    // "CAL_VOLTAGE_OFFSET",
    // "CAL_CURRENT_GAIN_LR",
    // "CAL_CURRENT_OFFSET_LR",
    // "CAL_CURRENT_GAIN_HR",
    // "CAL_CURRENT_OFFSET_HR",
    "EVENT_CODE",
    // "EVENT_COUNT",
    // "EVENT_READ",
    // "EVENT_OVERFLOW",
    // "EVENT_TIME",
    // "ERROR_TIME",
    // "FIRMWARE_WHOLE_CRC1",
    // "FIRMWARE_HMAC_SIGNATURE",
    // "FIRMWARE_IMAGE_SIZE",
    // "DISPLAY_LINE_3",
    // "DISPLAY_LINE_4",
]

// Register Address ////////////////////////////////////////////////////////////
MB_ADDR_PROTO_VERSION <- 0x0000;
MB_ADDR_FW_VERSION <- 0x0001;
MB_ADDR_SERIAL_NUM <- 0x0002;
MB_ADDR_CAPABILITIES <- 0x000C;
MB_ADDR_SEC_RESET <- 0x000E;
MB_ADDR_SEC_SLEEP <- 0x000F;
MB_ADDR_SEC_CHARGER_TYPE <- 0x0010;
MB_ADDR_SEC_CHARGER_FORM_FACTOR <- 0x0011;

MB_ADDR_ACTIVE <- 0x0040;
MB_ADDR_AUTHORIZE_TYPE <- 0x0041;
MB_ADDR_SESSION_TYPE <- 0x0042;
MB_ADDR_AUTHORIZE_DATA <- 0x0043;
MB_ADDR_AUTHORIZE_STROBE <- 0x0044;
MB_ADDR_POWER_LIMIT_CONTROL <- 0x0045;
MB_ADDR_POWER_LIMIT <- 0x0046;
MB_ADDR_UPDATE_RATE <- 0x0047;
MB_ADDR_TIME <- 0x0048;
MB_ADDR_SEC_STATE_RESET <- 0x004C;
MB_ADDR_COLD_LOAD_ENABLED <- 0x004D;
MB_ADDR_MIN_COLD_LOAD_TIME <- 0x004E;
MB_ADDR_MAX_COLD_LOAD_TIME <- 0x004F;
MB_ADDR_FIRMWARE_TRANSFER <- 0x0050;
MB_ADDR_FIRMWARE_WHOLE_CRC <- 0x0051;
MB_ADDR_FIRMWARE_BLOCK_CRC <- 0x0052;
MB_ADDR_FIRMWARE <- 0x0053;
MB_ADDR_FIRMWARE_NUM_BYTES <- 0x0085;

MB_ADDR_PROTOCOL_TYPE <- 0x00C0;
MB_ADDR_PROTOCOL_STATE <- 0x00C1;
MB_ADDR_RESET_REASON <- 0x00C2;
MB_ADDR_SEC_TEMP <- 0x00C4;
MB_ADDR_OTHER_TEMPS <- 0x00C8;
MB_ADDR_STATE_OF_CHARGE <- 0x00F0;
MB_ADDR_REMAINING_AUTHORIZATION <- 0x00F1;

MB_ADDR_REMAINING_CHARGE_TIME <- 0x00F4;
MB_ADDR_PERMANENT_ERROR_FLAG <- 0x00F6;
MB_ADDR_TEMP_ERROR <- 0x00F7;
MB_ADDR_ERROR_COUNT <- 0x00F8;
MB_ADDR_ERROR_CODE <- 0x00F9;
MB_ADDR_ERROR_DATA_1 <- 0x00FA;
MB_ADDR_ERROR_DATA_2 <- 0x00FB;
MB_ADDR_ERROR_DATA_3 <- 0x00FC;
MB_ADDR_ERROR_DATA_4 <- 0x00FD;
MB_ADDR_ERROR_READ <- 0x00FE;
MB_ADDR_ERROR_OVERFLOW <- 0x00FF;
MB_ADDR_GFCI_FAULTS_SESSION <- 0x0100;

MB_ADDR_LAST_READ_VOLTAGE <- 0x0104;
MB_ADDR_LAST_READ_CURRENT <- 0x0108;
MB_ADDR_ENERGY_TOTAL_FOREVER <- 0x010C;
MB_ADDR_ENERGY_TOTAL_RESET <- 0x0110;
MB_ADDR_ENERGY_TOTAL_CHARGE <- 0x0114;
MB_ADDR_ENERGY_TOTAL_PLUG <- 0x0118;
MB_ADDR_CHARGE_SESSION_COUNT_FOREVER <- 0x011C;
MB_ADDR_CHARGE_SESSION_COUNT_RESET <- 0x011E;
MB_ADDR_PLUG_SESSION_COUNT_FOREVER <- 0x0120;
MB_ADDR_PLUG_SESSION_COUNT_RESET <- 0x0122;
MB_ADDR_BOOT_COUNT_FOREVER <- 0x0124;
MB_ADDR_BOOT_COUNT_RESET <- 0x0125;
MB_ADDR_POWER_LOSS_COUNT_FOREVER <- 0x0126;
MB_ADDR_POWER_LOSS_COUNT_RESET <- 0x0127;
MB_ADDR_AUTO_RECLOSE_TIME_REMAINING <- 0x0128;
MB_ADDR_COLD_LOAD_TIME_REMAINING <- 0x0129;
MB_ADDR_FACTORY_PASSWORD <- 0x012A;
MB_ADDR_FACTORY_NAMEPLATE_RATING <- 0x012B;
MB_ADDR_CAL_VOLTAGE_GAIN <- 0x012C;
MB_ADDR_CAL_VOLTAGE_OFFSET <- 0x0130;
MB_ADDR_CAL_CURRENT_GAIN_LR <- 0x0134;
MB_ADDR_CAL_CURRENT_OFFSET_LR <- 0x0138;
MB_ADDR_CAL_CURRENT_GAIN_HR <- 0x013C;
MB_ADDR_CAL_CURRENT_OFFSET_HR <- 0x0140;
MB_ADDR_EVENT_CODE <- 0x0144;
MB_ADDR_EVENT_COUNT <- 0x0145;
MB_ADDR_EVENT_READ <- 0x0146;
MB_ADDR_EVENT_OVERFLOW <- 0x0147;
MB_ADDR_EVENT_TIME <- 0x0148;
MB_ADDR_ERROR_TIME <- 0x014C;
MB_ADDR_FIRMWARE_WHOLE_CRC1 <- 0x0150;
MB_ADDR_FIRMWARE_HMAC_SIGNATURE <- 0x0152;
MB_ADDR_FIRMWARE_IMAGE_SIZE <- 0x0162;

MB_ADDR_DISPLAY_LINE_3 <- 0x0170;
MB_ADDR_DISPLAY_LINE_4 <- 0x017A;


// Register Lengths ////////////////////////////////////////////////////////////
MB_LEN_PROTO_VERSION <- 1;
MB_LEN_FW_VERSION <- 1;
MB_LEN_SERIAL_NUM <- 10;
MB_LEN_CAPABILITIES <- 2;
MB_LEN_SEC_RESET <- 1;
MB_LEN_SEC_SLEEP <- 1;
MB_LEN_SEC_CHARGER_TYPE <- 1;
MB_LEN_SEC_CHARGER_FORM_FACTOR <- 1;

MB_LEN_ACTIVE <- 1;
MB_LEN_AUTHORIZE_TYPE <- 1;
MB_LEN_SESSION_TYPE <- 1;
MB_LEN_AUTHORIZE_DATA <- 1;
MB_LEN_AUTHORIZE_STROBE <- 1;
MB_LEN_POWER_LIMIT_CONTROL <- 1;
MB_LEN_POWER_LIMIT <- 1;
MB_LEN_UPDATE_RATE <- 1;
MB_LEN_TIME <- 4;
MB_LEN_SEC_STATE_RESET <- 1;
MB_LEN_COLD_LOAD_ENABLED <- 1;
MB_LEN_MIN_COLD_LOAD_TIME <- 1;
MB_LEN_MAX_COLD_LOAD_TIME <- 1;
MB_LEN_FIRMWARE_TRANSFER <- 1;
MB_LEN_FIRMWARE_WHOLE_CRC <- 1;
MB_LEN_FIRMWARE_BLOCK_CRC <- 1;
MB_LEN_FIRMWARE <- 50;
MB_LEN_FIRMWARE_NUM_BYTES <- 1;

MB_LEN_PROTOCOL_TYPE <- 1;
MB_LEN_PROTOCOL_STATE <- 1;
MB_LEN_RESET_REASON <- 1;
MB_LEN_SEC_TEMP <- 4;
MB_LEN_OTHER_TEMPS <- 40;
MB_LEN_STATE_OF_CHARGE <- 1;
MB_LEN_REMAINING_AUTHORIZATION <- 1;

MB_LEN_REMAINING_CHARGE_TIME <- 2;
MB_LEN_PERMANENT_ERROR_FLAG <- 1;
MB_LEN_TEMP_ERROR <- 1;
MB_LEN_ERROR_COUNT <- 1;
MB_LEN_ERROR_CODE <- 1;
MB_LEN_ERROR_DATA_1 <- 1;
MB_LEN_ERROR_DATA_2 <- 1;
MB_LEN_ERROR_DATA_3 <- 1;
MB_LEN_ERROR_DATA_4 <- 1;
MB_LEN_ERROR_READ <- 1;
MB_LEN_ERROR_OVERFLOW <- 1;
MB_LEN_GFCI_FAULTS_SESSION <- 1;

MB_LEN_LAST_READ_VOLTAGE <- 4;
MB_LEN_LAST_READ_CURRENT <- 4;
MB_LEN_ENERGY_TOTAL_FOREVER <- 4;
MB_LEN_ENERGY_TOTAL_RESET <- 4;
MB_LEN_ENERGY_TOTAL_CHARGE <- 4;
MB_LEN_ENERGY_TOTAL_PLUG <- 4;
MB_LEN_CHARGE_SESSION_COUNT_FOREVER <- 2;
MB_LEN_CHARGE_SESSION_COUNT_RESET <- 2;
MB_LEN_PLUG_SESSION_COUNT_FOREVER <- 2;
MB_LEN_PLUG_SESSION_COUNT_RESET <- 2;
MB_LEN_BOOT_COUNT_FOREVER <- 1;
MB_LEN_BOOT_COUNT_RESET <- 1;
MB_LEN_POWER_LOSS_COUNT_FOREVER <- 1;
MB_LEN_POWER_LOSS_COUNT_RESET <- 1;
MB_LEN_AUTO_RECLOSE_TIME_REMAINING <- 1;
MB_LEN_COLD_LOAD_TIME_REMAINING <- 1;
MB_LEN_FACTORY_PASSWORD <- 1;
MB_LEN_FACTORY_NAMEPLATE_RATING <- 1;
MB_LEN_CAL_VOLTAGE_GAIN <- 4;
MB_LEN_CAL_VOLTAGE_OFFSET <- 4;
MB_LEN_CAL_CURRENT_GAIN_LR <- 4;
MB_LEN_CAL_CURRENT_OFFSET_LR <- 4;
MB_LEN_CAL_CURRENT_GAIN_HR <- 4;
MB_LEN_CAL_CURRENT_OFFSET_HR <- 4;
MB_LEN_EVENT_CODE <- 1;
MB_LEN_EVENT_COUNT <- 1;
MB_LEN_EVENT_READ <- 1;
MB_LEN_EVENT_OVERFLOW <- 1;
MB_LEN_EVENT_TIME <- 4;
MB_LEN_ERROR_TIME <- 4;
MB_LEN_FIRMWARE_WHOLE_CRC1 <- 2;
MB_LEN_FIRMWARE_HMAC_SIGNATURE <- 16;
MB_LEN_FIRMWARE_IMAGE_SIZE <- 2;

MB_LEN_DISPLAY_LINE_3 <- 10;
MB_LEN_DISPLAY_LINE_4 <- 10;


// Register Data Types /////////////////////////////////////////////////////////
MB_TYPE_PROTO_VERSION <- UINT16;
MB_TYPE_FW_VERSION <- UINT16;
MB_TYPE_SERIAL_NUM <- STRING8;
MB_TYPE_CAPABILITIES <- UINT16;
MB_TYPE_SEC_RESET <- BOOL;
MB_TYPE_SEC_SLEEP <- UINT8;
MB_TYPE_SEC_CHARGER_TYPE <- UINT8;
MB_TYPE_SEC_CHARGER_FORM_FACTOR <- UINT8;

MB_TYPE_ACTIVE <- BOOL;
MB_TYPE_AUTHORIZE_TYPE <- UINT8;
MB_TYPE_SESSION_TYPE <- UINT8;
MB_TYPE_AUTHORIZE_DATA <- UINT16;
MB_TYPE_AUTHORIZE_STROBE <- BOOL;
MB_TYPE_POWER_LIMIT_CONTROL <- UINT8;
MB_TYPE_POWER_LIMIT <- UINT16;
MB_TYPE_UPDATE_RATE <- UINT16;
MB_TYPE_TIME <- UINT64;
MB_TYPE_SEC_STATE_RESET <- BOOL;
MB_TYPE_COLD_LOAD_ENABLED <- BOOL;
MB_TYPE_MIN_COLD_LOAD_TIME <- UINT16;
MB_TYPE_MAX_COLD_LOAD_TIME <- UINT16;
MB_TYPE_FIRMWARE_TRANSFER <- BOOL;
MB_TYPE_FIRMWARE_WHOLE_CRC <- UINT16;
MB_TYPE_FIRMWARE_BLOCK_CRC <- UINT16;
MB_TYPE_FIRMWARE <- UINT8;
MB_TYPE_FIRMWARE_NUM_BYTES <- UINT16;

MB_TYPE_PROTOCOL_TYPE <- UINT8;
MB_TYPE_PROTOCOL_STATE <- UINT8;
MB_TYPE_RESET_REASON <- UINT8;
MB_TYPE_SEC_TEMP <- FLOAT;
MB_TYPE_OTHER_TEMPS <- FLOAT;
MB_TYPE_STATE_OF_CHARGE <- SINT16;
MB_TYPE_REMAINING_AUTHORIZATION <- UINT16;

MB_TYPE_REMAINING_CHARGE_TIME <- UINT32;
MB_TYPE_PERMANENT_ERROR_FLAG <- BOOL;
MB_TYPE_TEMP_ERROR <- UINT16;
MB_TYPE_ERROR_COUNT <- UINT16;
MB_TYPE_ERROR_CODE <- UINT16;
MB_TYPE_ERROR_DATA_1 <- UINT16;
MB_TYPE_ERROR_DATA_2 <- UINT16;
MB_TYPE_ERROR_DATA_3 <- UINT16;
MB_TYPE_ERROR_DATA_4 <- UINT16;
MB_TYPE_ERROR_READ <- BOOL;
MB_TYPE_ERROR_OVERFLOW <- BOOL;
MB_TYPE_GFCI_FAULTS_SESSION <- UINT16;

MB_TYPE_LAST_READ_VOLTAGE <- FLOAT;
MB_TYPE_LAST_READ_CURRENT <- FLOAT;
MB_TYPE_ENERGY_TOTAL_FOREVER <- FLOAT;
MB_TYPE_ENERGY_TOTAL_RESET <- FLOAT;
MB_TYPE_ENERGY_TOTAL_CHARGE <- FLOAT;
MB_TYPE_ENERGY_TOTAL_PLUG <- FLOAT;
MB_TYPE_CHARGE_SESSION_COUNT_FOREVER <- UINT32;
MB_TYPE_CHARGE_SESSION_COUNT_RESET <- UINT32;
MB_TYPE_PLUG_SESSION_COUNT_FOREVER <- UINT32;
MB_TYPE_PLUG_SESSION_COUNT_RESET <- UINT32;
MB_TYPE_BOOT_COUNT_FOREVER <- UINT16;
MB_TYPE_BOOT_COUNT_RESET <- UINT16;
MB_TYPE_POWER_LOSS_COUNT_FOREVER <- UINT16;
MB_TYPE_POWER_LOSS_COUNT_RESET <- UINT16;
MB_TYPE_AUTO_RECLOSE_TIME_REMAINING <- UINT16;
MB_TYPE_COLD_LOAD_TIME_REMAINING <- UINT16;
MB_TYPE_FACTORY_PASSWORD <- UINT16;
MB_TYPE_FACTORY_NAMEPLATE_RATING <- UINT16;
MB_TYPE_CAL_VOLTAGE_GAIN <- FLOAT;
MB_TYPE_CAL_VOLTAGE_OFFSET <- FLOAT;
MB_TYPE_CAL_CURRENT_GAIN_LR <- FLOAT;
MB_TYPE_CAL_CURRENT_OFFSET_LR <- FLOAT;
MB_TYPE_CAL_CURRENT_GAIN_HR <- FLOAT;
MB_TYPE_CAL_CURRENT_OFFSET_HR <- FLOAT;
MB_TYPE_EVENT_CODE <- UINT16;
MB_TYPE_EVENT_COUNT <- UINT16;
MB_TYPE_EVENT_READ <- UINT16;
MB_TYPE_EVENT_OVERFLOW <- BOOL;
MB_TYPE_EVENT_TIME <- UINT64;
MB_TYPE_ERROR_TIME <- UINT64;
MB_TYPE_FIRMWARE_WHOLE_CRC1 <- UINT32;
MB_TYPE_FIRMWARE_HMAC_SIGNATURE <- UINT8;
MB_TYPE_FIRMWARE_IMAGE_SIZE <- UINT32;

MB_TYPE_DISPLAY_LINE_3 <- STRING8;
MB_TYPE_DISPLAY_LINE_4 <- STRING8;

// =============================================================================
// ------------------------------------------ END_CONSTANTS_AND_GLOBAL_VARIABLES
// ============================================================================}
